name: Docker ECR Cache
description: Cache Docker images in Amazon ECR
author: https://github.com/seek-oss
requirements:
  - docker
configuration:
  properties:
    build-args:
      type: [array, string]
    additional-build-args:
      type: string
    cache-on:
      type: [array, string]
    dockerfile:
      type: string
    ecr-name:
      type: string
    target:
      type: string
    max-age-days:
      type: number
    export-env-variable:
      type: string
  required: []
